;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file located at
;; https://gitlab.com/zzamboni/dot-doom/-/blob/master/doom.org
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
;; (setq user-full-name "John Doe"
;;      user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
;; (setq doom-theme 'doom-one)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
;; (setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
;; (setq display-line-numbers-type t)

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

(setq user-full-name "Kirill K"
      user-mail-address "2spybot@gmail.com")

(setq confirm-kill-emacs nil)

;; Whether display icons in the mode-line.
;; While using the server mode in GUI, should set the value explicitly.
(setq doom-modeline-icon t)

;; Whether display the icon for `major-mode'. It respects option `doom-modeline-icon'.
(setq doom-modeline-major-mode-icon t)

;; Whether display the colorful icon for `major-mode'.
;; It respects `nerd-icons-color-icons'.
(setq doom-modeline-major-mode-color-icon t)

;; Whether display the icon for the buffer state. It respects option `doom-modeline-icon'.
(setq doom-modeline-buffer-state-icon t)

;; Whether display the modification icon for the buffer.
;; It respects option `doom-modeline-icon' and option `doom-modeline-buffer-state-icon'.
(setq doom-modeline-buffer-modification-icon t)

;; Whether display the lsp icon. It respects option `doom-modeline-icon'.
(setq doom-modeline-lsp-icon t)

(setq doom-modeline-enable-word-count t)

(setq doom-theme 'catppuccin)

(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))

(add-to-list 'default-frame-alist '(alpha 93 83))

(let ((alternatives '(
                      "emacs.svg"
                      "doom-vapourwave.png"
                      "doomEmacsDracula.svg"
                      "logo-mini-doom.png"
                      )))
  (setq fancy-splash-image
        (concat doom-user-dir "images/"
                (nth (random (length alternatives)) alternatives))))

(setq doom-font (font-spec :family "JetBrainsMono Nerd Font" :size 15 :weight 'light)
      doom-variable-pitch-font (font-spec :family "Iosevka" :size 16)
      ;; doom-variable-pitch-font (font-spec :family "JetBrainsMono Nerd Font" :size 15)
      doom-big-font (font-spec :family "JetBrainsMono Nerd Font" :size 24))

(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))

(dolist (mode '(org-mode-hook
                term-mode-hook
                shell-mode-hook
                treemacs-mode-hook
                eshell-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))

(setq display-line-numbers-type 'relative)

(custom-set-faces! '(cursor :background "#F0A015"))

(custom-set-faces! '(org-list-dt :foreground "#F0A015"))

(custom-set-faces
  '(org-level-1 ((t (:inherit outline-1 :height 1.325))))
  '(org-level-2 ((t (:inherit outline-2 :height 1.125))))
  '(org-level-3 ((t (:inherit outline-3 :height 1.05 :foreground "#77D0E7"))))
  '(org-level-4 ((t (:inherit outline-4 :height 1.01))))
  '(org-level-5 ((t (:inherit outline-5 :height 1.01))))
  '(org-level-6 ((t (:inherit outline-6 :height 1.01))))
  '(org-level-7 ((t (:inherit outline-7 :height 1.01))))
  '(org-document-title ((t (:inherit outline-7 :bold t :height 1.625))))
)

(custom-set-faces!
    '(org-agenda-date :inherit outline-1 :height 1.15)
    '(org-agenda-date-today :inherit outline-2 :height 1.15)
    '(org-agenda-date-weekend :inherit outline-1 :height 1.15)
    '(org-agenda-date-weekend-today :inherit outline-2 :height 1.15)
    '(org-super-agenda-header :inherit custom-button :weight bold :height 1.05)
    '(org-link :foreground unspecified))

(map! "M-g g" #'avy-goto-line)
(map! "M-g M-g" #'avy-goto-line)

(map! :n "H" #'evil-first-non-blank)
(map! :n "L" #'evil-end-of-line)

(map! :n "M-z" #'+vterm/toggle)

(map! :n "M-q" #'kill-current-buffer)
(map! :n "M-n" #'next-buffer)
(map! :n "M-p" #'previous-buffer)

(after! evil-escape
  (setq evil-escape-key-sequence "jj"))

(map! :leader
      (:prefix ("n r" . "org-roam")
       :desc "Completion at point" "c" #'completion-at-point
       :desc "Find node"           "f" #'org-roam-node-find
       :desc "Show graph"          "g" #'org-roam-graph
       :desc "Insert node"         "i" #'org-roam-node-insert
       :desc "Capture to node"     "n" #'org-roam-capture
       :desc "Toggle roam buffer"  "r" #'org-roam-buffer-toggle))

(map! :n "C-f f" #'org-roam-node-find)
(map! :n "C-f r" #'org-roam-node-random)
(map! :n "C-f b" #'org-mark-ring-goto)

(setq org-directory "~/Documents/org/")
(setq org-default-notes-file "~/Documents/org/Agenda/Inbox.org")

(after! org (setq org-hide-emphasis-markers t))

(after! org
    (setq org-ellipsis "…"
          org-modern-hide-stars nil
          org-modern-star 'replace
          org-modern-replace-stars "⁖◉✳○❂✸◇◈"))

(after! org
  (setq org-agenda-files '(
                           "~/Documents/org/Agenda/Personal.org"
                           "~/Documents/org/Agenda/Projects.org"
                           "~/Documents/org/Agenda/Work.org"
                           "~/Documents/org/Agenda/Inbox.org"
                           )))

(after! org
    (setq org-roam-directory "~/Documents/org/roam/"
        org-roam-db-location "~/Documents/org/roam/org-roam.db"
        org-roam-graph-viewer "floorp")
)

(after! org
    (setq org-attach-id-dir "~/Documents/org/.attach"
        org-id-locations-file "~/Documents/org/.orgids")
)

(after! org
    (setq org-capture-templates
    '(("t" "Todo" entry (file+headline "~/Documents/org/Agenda/Inbox.org" "Tasks")
            "* TODO %?\n  %i\n  %a")
        ("j" "Journal" entry (file+datetree "~/Documents/org/Agenda/Inbox.org")
            "* %?\nEntered on %U\n  %i\n  %a")))
)

(after! org
    (setq org-roam-capture-templates
            '(("d" "default" plain
                "%?"
                :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
                :unnarrowed t)

            ("b" "book" plain
                "\n* Source\n\nAuthor: %^{Author}\nTitle: ${title}\nYear: %^{Year}\n\n* Summary\n\n%?"
                :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
                :unnarrowed t)

            ("n" "notes" plain (file "~/Documents/org/roam/Templates/NoteTemplate.org")
                :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
                :unnarrowed t)
        )
    )
)

(after! org
    (setq org-tag-alist
        '(;;Places
            ("@home" . ?H)
            ("@work" . ?W)

            ;; Activities
            ("@health" . ?h)
            ("@investing" . ?i)
            ("@learning" . ?l)
            ("@youtube" . ?y)
            ("@planing" . ?n)
            ("@programming" . ?p)
            ("@writing" . ?w)
            ("@shopping" . ?s)
            ("@message" . ?m)
            ("@call" . ?a)))
)

(after! org
    (setq calendar-week-start-day 1)

    (setq org-agenda-skip-function-global '(org-agenda-skip-entry-if 'todo 'done))

    (setq org-agenda-span 1
            org-agenda-start-day "+0d")

    (setq org-agenda-custom-commands
        '(("p" "Planning"
                ((tags-todo "+@planning"
                                ((org-agenda-overriding-header "Planning Tasks")))
                (tags-todo "-{.*}"
                                ((org-agenda-overriding-header "Untagged Tasks")))
                (todo ".*" ((org-agenda-files '("~/Documents/org/Agenda/Inbox.org"))
                                (org-agenda-overriding-header "Unprocessed Inbox Items")))))

            ("d" "Daily Agenda"
                ((agenda "" ((org-agenda-span 'day)
                        (org-deadline-warning-days 7)))
                (tags-todo "+PRIORITY=\"A\""
                        ((org-agenda-overriding-header "High Priority Tasks")))))

            ("w" "Weekly Review"
                ((agenda ""
                        ((org-agenda-overriding-header "Completed Tasks")
                        (org-agenda-skip-function '(org-agenda-skip-entry-if 'nottodo 'done))
                        (org-agenda-span 'week)))

                (agenda ""
                        ((org-agenda-overriding-header "Unfinished Scheduled Tasks")
                        (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                        (org-agenda-span 'week)))))))

)

(setq olivetti-style 'fancy
      olivetti-margin-width 120)
(setq-default olivetti-body-width 120)

(defun org-agenda-open-hook ()
  (olivetti-mode))

(add-hook 'org-agenda-mode-hook 'org-agenda-open-hook)
(add-hook 'org-mode-hook 'org-agenda-open-hook)

(use-package! org-auto-tangle
  :defer t
  :hook (org-mode . org-auto-tangle-mode)
  :config
  (setq org-auto-tangle-default t))

(after! org
    (setq org-use-property-inheritance t
          org-latex-hyperref-template "\\hypersetup{\n pdfauthor={%a},\n pdftitle={%t},\n colorlinks=true}\n"
          org-latex-pdf-process '("tectonic -X compile --outdir=%o -Z shell-escape -Z continue-on-errors %f"))

)
