[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell /usr/bin/fish --block'
# run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
